### ISSUE TITLE
Neural style transfer on TensorFlow

### ISSUE THREAD

**Issue by sagar-m** [anishathalye/neural-style#123]
Hi Anish, I tried neural style transfer on tensorflow, and I am stuck with the following error, not sure why. My implementation is almost exactly as it is in this [link](http://www.chioka.in/tensorflow-implementation-neural-algorithm-of-artistic-style).Thanks!

```
tf.reset_default_graph()

sess = tf.InteractiveSession()

sess.run(tf.initialize_all_variables())

sess.run(model['input'].assign(content_image))
Traceback (most recent call last):

File "<ipython-input-103-ee79f3610a98>", line 1, in <module>
sess.run(model['input'].assign(content_image))

File "/Users/sherrymukim/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
run_metadata_ptr)

File "/Users/sherrymukim/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1105, in _run
self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)

File "/Users/sherrymukim/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 414, in __init__
self._fetch_mapper = _FetchMapper.for_fetch(fetches)

File "/Users/sherrymukim/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 242, in for_fetch
return _ElementFetchMapper(fetches, contraction_fn)

File "/Users/sherrymukim/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 278, in __init__
'Tensor. (%s)' % (fetch, str(e)))

ValueError: Fetch argument <tf.tensor 'assign_5:0'="" shape="(1," 300,="" 400,="" 3)="" dtype="float32_ref"> cannot be interpreted as a Tensor. (Tensor Tensor("Assign_5:0", shape=(1, 300, 400, 3), dtype=float32_ref) is not an element of this graph.)
```

**Comment by anishathalye** [comment]
Oh hmm, for a moment, I thought you were asking about my implementation. I'm not the author of the blog post of chioka.in, so I can't provide support for it.

**Comment by sagar-m** [comment]
Hi, I noticed that you have also implemented NST on tensorflow, and thus maybe have an idea what is going wrong here! Thank you anyways.

**Comment by sagar-m** [comment]
Thanks a ton. I was googling the entire error statement, and thus never came across this post! Appreciate it.
