### ISSUE TITLE
imagenet-vgg-verydeep-19.mat no longer matches checksum

### ISSUE THREAD

**Issue by evanthomas** [anishathalye/neural-style#141]
The model downloaded via the link:
http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat
now has different checksum.

It won't load either:
```
 python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --network imagenet-vgg-verydeep-19.mat --output blah16.jpg
Traceback (most recent call last):
  File "neural_style.py", line 224, in <module>
    main()
  File "neural_style.py", line 184, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/evan/neurosim/neural-style/stylize.py", line 35, in stylize
    vgg_weights, vgg_mean_pixel = vgg.load_net(network)
  File "/home/evan/neurosim/neural-style/vgg.py", line 26, in load_net
    raise ValueError("You're using the wrong VGG19 data. Please follow the instructions in the README to download the correct data.")
ValueError: You're using the wrong VGG19 data. Please follow the instructions in the README to download the correct data.
```

**Comment by anishathalye** [comment]
I did a fresh download:

```
$ wget http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat
$ md5sum imagenet-vgg-verydeep-19.mat
8ee3263992981a1d26e73b3ca028a123  imagenet-vgg-verydeep-19.mat
```

Looks fine to me -- maybe your download is corrupted?

**Comment by evanthomas** [comment]
Hmm, OK. Works for me too now.  I initially did download with chrome (twice), maybe that had something to do with it.

Sorry to waste your time.
