### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by markeroon** [anishathalye/neural-style#43]
python neural_style.py --content examples/1-content.jpg --styles examples/1-style.jpg --output output0.jpg

```
Traceback (most recent call last):
  File "neural_style.py", line 152, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/markb/Dev/neural-style/stylize.py", line 41, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/home/markb/Dev/neural-style/vgg.py", line 26, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'
```

**Comment by anishathalye** [comment]
See #4 #6 #12 #25 #39

**Comment by markeroon** [comment]
Updating vgg-imagenet fixed it, thank you.
