### ISSUE TITLE
ValueError: Shape (1, 199, 153) must have rank 4

### ISSUE THREAD

**Issue by liudonglei** [anishathalye/neural-style#45]
Hi, the example 1 in the Readme.md is OK on my laptop. It is interesting!
but, when I try this code with my picture, it raises the following error:
----------------------------------
$ python neural_style.py --content LiX.jpg  --styles 1-style.jpg --output 2-output.jpg
Traceback (most recent call last):
  File "neural_style.py", line 152, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/Users/ldl/Documents/neural-style/stylize.py", line 41, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/Users/ldl/Documents/neural-style/vgg.py", line 39, in net
    current = _conv_layer(current, kernels, bias)
  File "/Users/ldl/Documents/neural-style/vgg.py", line 52, in _conv_layer
    padding='SAME')
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
    data_format=data_format, name=name)
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 209, in conv2d_shape
    input_shape = op.inputs[0].get_shape().with_rank(4)
  File "/Users/ldl/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 641, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (1, 199, 153) must have rank 4

In my laptop
tensorflow: version 0.10
-----------------------------------------------
I don't know how to modify it to get it work.

**Comment by anishathalye** [comment]
Would you mind sharing the `LiX.jpg` file? It would make debugging easier.

**Comment by liudonglei** [comment]
http://photo.weibo.com/1725477250/wbphotos/large/mid/4051089114716424/pid/66d8b182jw1fali9m65vbj204905jq2t

it likes my github photo

**Comment by anishathalye** [comment]
Hm, could you just email it to me? I can't see that.

`me@{my github username}.com`

**Comment by anishathalye** [comment]
Ah, okay, this was something I had noticed a while ago but was too lazy to fix.

Fixed in 4bfb9efb1f0e955922889187727e33185e97d934.

**Comment by liudonglei** [comment]
Yes, It works now. Thanks very much for your enthusiasm
--------
$ python neural_style.py --content LiX.jpg  --styles 1-style.jpg --output 2-output.jpg --iterations 10
Iteration 1/10
Iteration 2/10
Iteration 3/10
Iteration 4/10
Iteration 5/10
Iteration 6/10
Iteration 7/10
Iteration 8/10
Iteration 9/10
Iteration 10/10
  content loss: 4.45742e+06
    style loss: 8.36498e+06
       tv loss: 143511
    total loss: 1.29659e+07
