### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by ryh95** [anishathalye/neural-style#46]
I run the command 

`python neural_style.py --content ./examples/1-content.jpg --styles ./examples/1-style.jpg --output ./examples/1-output.jpg`

but got this error 

```
Traceback (most recent call last):
  File "neural_style.py", line 156, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/shelly/gitProjects/neural-style/stylize.py", line 41, in stylize
    net, mean_pixel = vgg.net(network, image)
  File "/home/shelly/gitProjects/neural-style/vgg.py", line 25, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'
```

maybe a bug ?

**Comment by anishathalye** [comment]
See #4 #6 #12 #25 #39 #43

**Comment by ryh95** [comment]
I used your link  given at the bottom of the readme and updated the pre-trained network

but got this error

```
Traceback (most recent call last):
  File "neural_style.py", line 156, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/shelly/gitProjects/neural-style/stylize.py", line 56, in stylize
    gram = np.matmul(features.T, features) / features.size
AttributeError: 'module' object has no attribute 'matmul'


```

**Comment by anishathalye** [comment]
Hmm, maybe wrong numpy version? Which one are you using?

```bash
python -c 'import numpy; print(numpy.__version__)'
```

`np.matmul` was added in 1.10.0.

**Comment by ryh95** [comment]
Yes, my numpy is too old and I have updated it 

```
python -c 'import numpy; print(numpy.__version__)'
1.11.2
```

then I got this error 

```
Traceback (most recent call last):
  File "neural_style.py", line 156, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/shelly/gitProjects/neural-style/stylize.py", line 117, in stylize
    train_step.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1579, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3808, in _run_using_default_session
    session.run(operation, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,256,134,100]
	 [[Node: Conv2D_7 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Relu_6, Const_7)]]

Caused by op u'Conv2D_7', defined at:
  File "neural_style.py", line 156, in <module>
    main()
  File "neural_style.py", line 130, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/home/shelly/gitProjects/neural-style/stylize.py", line 68, in stylize
    net, _ = vgg.net(network, image)
  File "/home/shelly/gitProjects/neural-style/vgg.py", line 39, in net
    current = _conv_layer(current, kernels, bias)
  File "/home/shelly/gitProjects/neural-style/vgg.py", line 52, in _conv_layer
    padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 396, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,256,134,100]
	 [[Node: Conv2D_7 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Relu_6, Const_7)]]
```

Is that means my Geforce gtx 750 ti is too poor to run this program?

**Comment by anishathalye** [comment]
The amount of memory you need is dependent on the size of the output image (you can set this with the command-line arguments; run the program with `--help` for more details).

See #20 #21 #28 for more details / related discussion.

**Comment by ryh95** [comment]
thank you, I really appreciate on your patience 
my hardware is i5 8G ram with gtx 750 ti
I use the `--width 100 ` to reduce the size of output and it works well
the picture size I test is the example you provided which content is 400\*533 and style is 640\*507
my question is 
in your opinion if I don't reduce the output and still I use your examples as input, what kind of hardware should I use in order to get the output in a reasonable time.

**Comment by anishathalye** [comment]
I'm not sure, I haven't tried running this on anything besides my Titan X and GTX 680.
