### ISSUE TITLE
Expecting matrix error

### ISSUE THREAD

**Issue by gonzalolc** [anishathalye/neural-style#64]
Hello
When runing the script i get this error.

> MacBook-Pro-de-Gonzalo:deepstyle Gonz$ python neural_style.py --content /Users/Gonz/Desktop/rigoOriginal.jpg --styles /Users/Gonz/Desktop/textura.jpg --output /Users/Gonz/Desktop/chida.jpg
Traceback (most recent call last):
  File "neural_style.py", line 206, in <module>
    main()
  File "neural_style.py", line 177, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/Users/Gonz/Desktop/deepstyle/stylize.py", line 39, in stylize
    vgg_weights, vgg_mean_pixel = vgg.load_net(network)
  File "/Users/Gonz/Desktop/deepstyle/vgg.py", line 23, in load_net
    data = scipy.io.loadmat(data_path)
  File "/usr/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 136, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/usr/local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "scipy/io/matlab/mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:7119)
  File "scipy/io/matlab/mio5_utils.pyx", line 719, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:6517)
  File "scipy/io/matlab/mio5_utils.pyx", line 892, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:8922)
  File "scipy/io/matlab/mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:6027)
  File "scipy/io/matlab/mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:6547)
  File "scipy/io/matlab/mio5_utils.pyx", line 967, in scipy.io.matlab.mio5_utils.VarReader5.read_struct (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:9877)
  File "scipy/io/matlab/mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:6027)
  File "scipy/io/matlab/mio5_utils.pyx", line 719, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:6517)
  File "scipy/io/matlab/mio5_utils.pyx", line 892, in scipy.io.matlab.mio5_utils.VarReader5.read_cells (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:8922)
  File "scipy/io/matlab/mio5_utils.pyx", line 664, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/io/matlab/mio5_utils.c:5851)
TypeError: Expecting matrix here

Don't know where it comes from.
Thank you @anishathalye  for this great implementation!!

UPDATE!
I know for shure the error comes when loading the vgg model in scipy.io.loadmat

**Comment by anishathalye** [comment]
Uh no idea what's causing that. Are you using the right VGG? Do the MD5s match the readme?
