### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by salimmj** [anishathalye/neural-style#69]
```
$ python neural_style.py --content images/columbianight.jpg --styles styles/starry_night.jpg --output output/starry_columbia.jpg
Traceback (most recent call last):
  File "neural_style.py", line 206, in <module>
    main()
  File "neural_style.py", line 177, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "/Users/salimmjahad/Desktop/neural-style/stylize.py", line 39, in stylize
    vgg_weights, vgg_mean_pixel = vgg.load_net(network)
  File "/Users/salimmjahad/Desktop/neural-style/vgg.py", line 24, in load_net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'
```

**Comment by ginsongsong** [comment]
Maybe you should try beta16 version imagenet-vgg-verydeep-19 model
http://www.vlfeat.org/matconvnet/models/beta16/imagenet-vgg-verydeep-19.mat

**Comment by anishathalye** [comment]
Also, this has been asked a couple times before: #4 #6 #12 #25 #39 #43 #46
